from enum import Enum


class PythonSentimentType(str, Enum):
    POLARITY = "POLARITY"
    SUBJECTIVITY = "SUBJECTIVITY"
    TTLABS_POLARITY = "TTLABS_POLARITY"
    TEXTBLOB_POLARITY = "TEXTBLOB_POLARITY"
    TEXTBLOB_SUBJECTIVITY = "TEXTBLOB_SUBJECTIVITY"
