from enum import Enum


class SentimentType(str, Enum):
    POLARITY = "POLARITY"
    SUBJECTIVITY = "SUBJECTIVITY"
    TEXTBLOB_POLARITY = "TEXTBLOB_POLARITY"
    TEXTBLOB_SUBJECTIVITY= "TEXTBLOB_SUBJECTIVITY"

